=== OmnigenNarra/narra-webapp-backend/src/narra_backend/static/schemas/validator.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "additionalProperties": false,
  "definitions": {
    "validationGlobalItem": {
      "additionalProperties": false,
      "properties": {
        "Messages": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "Verdict": {
          "type": "integer"
        }
      },
      "required": [
        "Messages",
        "Verdict"
      ],
      "type": "object"
    },
    "validationLinkEntry": {
      "additionalProperties": false,
      "properties": {
        "InNode": {
          "type": "string"
        },
        "InPin": {
          "type": "integer"
        },
        "Messages": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "OutNode": {
          "type": "string"
        },
        "OutPin": {
          "type": "integer"
        },
        "Verdict": {
          "type": "integer"
        }
      },
      "required": [
        "InNode",
        "InPin",
        "Messages",
        "OutNode",
        "OutPin",
        "Verdict"
      ],
      "type": "object"
    },
    "validationNodeEntry": {
      "additionalProperties": false,
      "properties": {
        "Fields": {
          "items": {
            "type": "integer"
          },
          "type": "array"
        },
        "Id": {
          "type": "string"
        },
        "Messages": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "Verdict": {
          "type": "integer"
        }
      },
      "required": [
        "Fields",
        "Id",
        "Messages",
        "Verdict"
      ],
      "type": "object"
    },
    "validationVariantEntry": {
      "items": {
        "type": "string"
      },
      "type": "array"
    }
  },
  "properties": {
    "Global": {
      "items": {
        "$ref": "#/definitions/validationGlobalItem"
      },
      "type": "array"
    },
    "Links": {
      "items": {
        "$ref": "#/definitions/validationLinkEntry"
      },
      "type": "array"
    },
    "Nodes": {
      "items": {
        "$ref": "#/definitions/validationNodeEntry"
      },
      "type": "array"
    },
    "Variants": {
      "items": {
        "$ref": "#/definitions/validationVariantEntry"
      },
      "type": "array"
    }
  },
  "required": [
    "Global",
    "Links",
    "Nodes",
    "Variants"
  ],
  "type": "object"
}

=== OmnigenNarra/narra-webapp-backend/src/doc/API/examples/package-validate-resp.json
{
  "Global": [],
  "Links": [
    {
      "InNode": "NStoryBlock_Action_2",
      "InPin": 0,
      "Messages": [
        "Link is coexecuted with a link to End",
        "Link is coexecuted with a link to End"
      ],
      "OutNode": "NStoryBlock_Option_0",
      "OutPin": 0,
      "Verdict": 2
    },
    {
      "InNode": "NStoryBlock_Fact_0",
      "InPin": 1,
      "Messages": [
        "Link creates an infinite loop!",
        "Link creates an infinite loop!",
        "Link creates an infinite loop!",
        "Link creates an infinite loop!",
        "Link creates an infinite loop!",
        "Link creates an infinite loop!",
        "Link creates an infinite loop!",
        "Link creates an infinite loop!",
        "Link creates an infinite loop!",
        "Link creates an infinite loop!",
        "Link creates an infinite loop!",
        "Link creates an infinite loop!",
        "Link creates an infinite loop!",
        "Link creates an infinite loop!",
        "Link creates an infinite loop!",
        "Link creates an infinite loop!",
        "Link creates an infinite loop!",
        "Link creates an infinite loop!"
      ],
      "OutNode": "NStoryBlock_Option_1",
      "OutPin": 0,
      "Verdict": 2
    },
    {
      "InNode": "NStoryBlock_Event_0",
      "InPin": 0,
      "Messages": [
        "Link is coexecuted with a link to End"
      ],
      "OutNode": "NStoryBlock_Condition_0",
      "OutPin": 1,
      "Verdict": 2
    }
  ],
  "Nodes": [
    {
      "Fields": [
        0,
        0
      ],
      "Id": "NStoryBlock_Action_3",
      "Messages": [],
      "Verdict": 0
    },
    {
      "Fields": [
        0
      ],
      "Id": "NStoryBlock_End_0",
      "Messages": [],
      "Verdict": 0
    },
    {
      "Fields": [],
      "Id": "NStoryBlock_Condition_3",
      "Messages": [
        "Node unreachable"
      ],
      "Verdict": 1
    },
    {
      "Fields": [
        0
      ],
      "Id": "NStoryBlock_End_2",
      "Messages": [],
      "Verdict": 0
    },
    {
      "Fields": [],
      "Id": "NCustomStoryBlock_Test_0",
      "Messages": [],
      "Verdict": 0
    },
    {
      "Fields": [],
      "Id": "NStoryBlock_Condition_2",
      "Messages": [
        "End unreachable in the following variant:\nNStoryBlock_Condition_0: 0\nNStoryBlock_Condition_1: 0\nNStoryBlock_Condition_2: 0\nNStoryBlock_Start_0: 1\n",
        "End unreachable in the following variant:\nNStoryBlock_Condition_0: 0\nNStoryBlock_Condition_1: 0\nNStoryBlock_Condition_2: 1\nNStoryBlock_Start_0: 1\n",
        "End unreachable in the following variant:\nNStoryBlock_Condition_0: 0\nNStoryBlock_Condition_1: 1\nNStoryBlock_Condition_2: 0\nNStoryBlock_Start_0: 1\n",
        "End unreachable in the following variant:\nNStoryBlock_Condition_0: 0\nNStoryBlock_Condition_1: 1\nNStoryBlock_Condition_2: 1\nNStoryBlock_Start_0: 1\n",
        "End unreachable in the following variant:\nNStoryBlock_Condition_0: 0\nNStoryBlock_Condition_1: 2\nNStoryBlock_Condition_2: 0\nNStoryBlock_Start_0: 1\n",
        "End unreachable in the following variant:\nNStoryBlock_Condition_0: 0\nNStoryBlock_Condition_1: 2\nNStoryBlock_Condition_2: 1\nNStoryBlock_Start_0: 1\n",
        "End unreachable in the following variant:\nNStoryBlock_Condition_0: 1\nNStoryBlock_Condition_1: 0\nNStoryBlock_Condition_2: 0\nNStoryBlock_Start_0: 1\n",
        "End unreachable in the following variant:\nNStoryBlock_Condition_0: 1\nNStoryBlock_Condition_1: 0\nNStoryBlock_Condition_2: 1\nNStoryBlock_Start_0: 1\n",
        "End unreachable in the following variant:\nNStoryBlock_Condition_0: 1\nNStoryBlock_Condition_1: 1\nNStoryBlock_Condition_2: 0\nNStoryBlock_Start_0: 1\n",
        "End unreachable in the following variant:\nNStoryBlock_Condition_0: 1\nNStoryBlock_Condition_1: 1\nNStoryBlock_Condition_2: 1\nNStoryBlock_Start_0: 1\n",
        "End unreachable in the following variant:\nNStoryBlock_Condition_0: 1\nNStoryBlock_Condition_1: 2\nNStoryBlock_Condition_2: 0\nNStoryBlock_Start_0: 1\n",
        "End unreachable in the following variant:\nNStoryBlock_Condition_0: 1\nNStoryBlock_Condition_1: 2\nNStoryBlock_Condition_2: 1\nNStoryBlock_Start_0: 1\n"
      ],
      "Verdict": 1
    },
    {
      "Fields": [
        0
      ],
      "Id": "NStoryBlock_Objective_1",
      "Messages": [],
      "Verdict": 0
    },
    {
      "Fields": [],
      "Id": "NStoryBlock_Pause_0",
      "Messages": [],
      "Verdict": 0
    },
    {
      "Fields": [
        0,
        0,
        0
      ],
      "Id": "NStoryBlock_Sound_0",
      "Messages": [],
      "Verdict": 0
    },
    {
      "Fields": [],
      "Id": "NStoryBlock_Start_0",
      "Messages": [
        "End unreachable in the following variant:\nNStoryBlock_Condition_0: 0\nNStoryBlock_Condition_1: 0\nNStoryBlock_Condition_2: 0\nNStoryBlock_Start_0: 1\n",
        "End unreachable in the following variant:\nNStoryBlock_Condition_0: 0\nNStoryBlock_Condition_1: 0\nNStoryBlock_Condition_2: 1\nNStoryBlock_Start_0: 1\n",
        "End unreachable in the following variant:\nNStoryBlock_Condition_0: 0\nNStoryBlock_Condition_1: 1\nNStoryBlock_Condition_2: 0\nNStoryBlock_Start_0: 1\n",
        "End unreachable in the following variant:\nNStoryBlock_Condition_0: 0\nNStoryBlock_Condition_1: 1\nNStoryBlock_Condition_2: 1\nNStoryBlock_Start_0: 1\n",
        "End unreachable in the following variant:\nNStoryBlock_Condition_0: 0\nNStoryBlock_Condition_1: 2\nNStoryBlock_Condition_2: 0\nNStoryBlock_Start_0: 1\n",
        "End unreachable in the following variant:\nNStoryBlock_Condition_0: 0\nNStoryBlock_Condition_1: 2\nNStoryBlock_Condition_2: 1\nNStoryBlock_Start_0: 1\n",
        "End unreachable in the following variant:\nNStoryBlock_Condition_0: 1\nNStoryBlock_Condition_1: 0\nNStoryBlock_Condition_2: 0\nNStoryBlock_Start_0: 1\n",
        "End unreachable in the following variant:\nNStoryBlock_Condition_0: 1\nNStoryBlock_Condition_1: 0\nNStoryBlock_Condition_2: 1\nNStoryBlock_Start_0: 1\n",
        "End unreachable in the following variant:\nNStoryBlock_Condition_0: 1\nNStoryBlock_Condition_1: 1\nNStoryBlock_Condition_2: 0\nNStoryBlock_Start_0: 1\n",
        "End unreachable in the following variant:\nNStoryBlock_Condition_0: 1\nNStoryBlock_Condition_1: 1\nNStoryBlock_Condition_2: 1\nNStoryBlock_Start_0: 1\n",
        "End unreachable in the following variant:\nNStoryBlock_Condition_0: 1\nNStoryBlock_Condition_1: 2\nNStoryBlock_Condition_2: 0\nNStoryBlock_Start_0: 1\n",
        "End unreachable in the following variant:\nNStoryBlock_Condition_0: 1\nNStoryBlock_Condition_1: 2\nNStoryBlock_Condition_2: 1\nNStoryBlock_Start_0: 1\n"
      ],
      "Verdict": 1
    },
    {
      "Fields": [],
      "Id": "NStoryBlock_Action_0",
      "Messages": [
        "Node unreachable"
      ],
      "Verdict": 1
    },
    {
      "Fields": [
        0,
        2,
        1
      ],
      "Id": "NStoryBlock_Option_0",
      "Messages": [
        "Missing label",
        "Missing Character"
      ],
      "Verdict": 2
    },
    {
      "Fields": [
        0
      ],
      "Id": "NStoryBlock_Condition_0",
      "Messages": [
        "End unreachable in the following variant:\nNStoryBlock_Condition_0: 0\nNStoryBlock_Condition_1: 0\nNStoryBlock_Condition_2: 0\nNStoryBlock_Start_0: 1\n",
        "End unreachable in the following variant:\nNStoryBlock_Condition_0: 0\nNStoryBlock_Condition_1: 0\nNStoryBlock_Condition_2: 1\nNStoryBlock_Start_0: 1\n",
        "End unreachable in the following variant:\nNStoryBlock_Condition_0: 0\nNStoryBlock_Condition_1: 1\nNStoryBlock_Condition_2: 0\nNStoryBlock_Start_0: 1\n",
        "End unreachable in the following variant:\nNStoryBlock_Condition_0: 0\nNStoryBlock_Condition_1: 1\nNStoryBlock_Condition_2: 1\nNStoryBlock_Start_0: 1\n",
        "End unreachable in the following variant:\nNStoryBlock_Condition_0: 0\nNStoryBlock_Condition_1: 2\nNStoryBlock_Condition_2: 0\nNStoryBlock_Start_0: 1\n",
        "End unreachable in the following variant:\nNStoryBlock_Condition_0: 0\nNStoryBlock_Condition_1: 2\nNStoryBlock_Condition_2: 1\nNStoryBlock_Start_0: 1\n",
        "End unreachable in the following variant:\nNStoryBlock_Condition_0: 1\nNStoryBlock_Condition_1: 0\nNStoryBlock_Condition_2: 0\nNStoryBlock_Start_0: 1\n",
        "End unreachable in the following variant:\nNStoryBlock_Condition_0: 1\nNStoryBlock_Condition_1: 0\nNStoryBlock_Condition_2: 1\nNStoryBlock_Start_0: 1\n",
        "End unreachable in the following variant:\nNStoryBlock_Condition_0: 1\nNStoryBlock_Condition_1: 1\nNStoryBlock_Condition_2: 0\nNStoryBlock_Start_0: 1\n",
        "End unreachable in the following variant:\nNStoryBlock_Condition_0: 1\nNStoryBlock_Condition_1: 1\nNStoryBlock_Condition_2: 1\nNStoryBlock_Start_0: 1\n",
        "End unreachable in the following variant:\nNStoryBlock_Condition_0: 1\nNStoryBlock_Condition_1: 2\nNStoryBlock_Condition_2: 0\nNStoryBlock_Start_0: 1\n",
        "End unreachable in the following variant:\nNStoryBlock_Condition_0: 1\nNStoryBlock_Condition_1: 2\nNStoryBlock_Condition_2: 1\nNStoryBlock_Start_0: 1\n"
      ],
      "Verdict": 1
    },
    {
      "Fields": [],
      "Id": "NStoryBlock_Condition_1",
      "Messages": [
        "End unreachable in the following variant:\nNStoryBlock_Condition_0: 0\nNStoryBlock_Condition_1: 0\nNStoryBlock_Condition_2: 0\nNStoryBlock_Start_0: 1\n",
        "End unreachable in the following variant:\nNStoryBlock_Condition_0: 0\nNStoryBlock_Condition_1: 0\nNStoryBlock_Condition_2: 1\nNStoryBlock_Start_0: 1\n",
        "End unreachable in the following variant:\nNStoryBlock_Condition_0: 0\nNStoryBlock_Condition_1: 1\nNStoryBlock_Condition_2: 0\nNStoryBlock_Start_0: 1\n",
