=== OmnigenNarra/narra-webapp-backend/src/doc/API/schemas/releaseuids-add-resp.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "additionalProperties": false,
  "properties": {
    "ctime": {
      "format": "datetime",
      "type": "string"
    },
    "id": {
      "type": "integer"
    },
    "organization": {
      "additionalProperties": false,
      "properties": {
        "id": {
          "type": "integer"
        },
        "name": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "name"
      ],
      "type": "object"
    },
    "release": {
      "additionalProperties": false,
      "properties": {
        "changes": {
          "type": "string"
        },
        "id": {
          "type": "integer"
        },
        "release_ver": {
          "type": "string"
        },
        "unreal_ver": {
          "type": "string"
        }
      },
      "required": [
        "changes",
        "id",
        "release_ver",
        "unreal_ver"
      ],
      "type": "object"
    },
    "uid": {
      "type": "string"
    },
    "url": {
      "type": "string"
    }
  },
  "required": [
    "ctime",
    "id",
    "organization",
    "release",
    "uid",
    "url"
  ],
  "type": "object"
}

=== OmnigenNarra/narra-webapp-backend/src/doc/API/examples/releaseuids-add-resp.json
{
  "ctime": "2019-12-03T10:41:33.326684Z",
  "id": 2,
  "organization": {
    "id": 4,
    "name": "docs-validator"
  },
  "release": {
    "changes": "",
    "id": 27,
    "release_ver": "R#920659",
    "unreal_ver": "0.07972693815579912"
  },
  "uid": "1_CL2_MRSZwpQk}y^‾3nYtjG7|DfNsOxeH.qlVi8I9!:1rEhcBX]bz6-K[gL$5mv",
  "url": ""
}

=== OmnigenNarra/narra-webapp-backend/src/doc/API/examples/releaseuids-list-resp.json
[
  {
    "ctime": "2019-12-03T10:33:01.624936Z",
    "id": 1,
    "organization": {
      "id": 4,
      "name": "docs-validator"
    },
    "release": {
      "changes": "",
      "id": 26,
      "release_ver": "R#292163",
      "unreal_ver": "0.2939398293292702"
    },
    "uid": "4_0.2939398293292702_R#292163_OLfwdIPU6~D08opGNqSZsX7J2nCk.WmzHA",
    "url": ""
  },
  {
    "ctime": "2019-12-03T10:41:33.326684Z",
    "id": 2,
    "organization": {
      "id": 4,
      "name": "docs-validator"
    },
    "release": {
      "changes": "",
      "id": 27,
      "release_ver": "R#920659",
      "unreal_ver": "0.07972693815579912"
    },
    "uid": "",
    "url": ""
  }
]
